const translations = {
  en: {
    nav_services: "Services",
    nav_work: "Work",
    nav_process: "Process",
    nav_testimonials: "Testimonials",
    nav_faq: "FAQ",
    nav_contact: "Contact",
    toggle_theme: "Dark mode",
    hero_eyebrow: "iOS Studio · MVP · Design · Backend",
    hero_title: "iOS MVPs for startups — shipped fast, built right.",
    hero_subtitle: "We turn ideas into investor‑ready products with clear scope, premium design, and reliable engineering.",
    hero_badge_1: "Fast MVP delivery",
    hero_badge_2: "Product thinking",
    hero_badge_3: "Senior iOS team",
    hero_mockup: "iPhone mockup placeholder",
    cta_primary: "Book a Call",
    cta_secondary: "Get a Quote",
    services_title: "Productized Services",
    services_subtitle: "Clear packages with deliverables, best‑fit, and starting budgets.",
    service_what: "What you get",
    service_best: "Best for",
    service1_title: "MVP Sprint (2–4 weeks)",
    service1_price: "from €X",
    service1_get_1: "Core flows + onboarding",
    service1_get_2: "Clickable prototype + backlog",
    service1_get_3: "TestFlight build",
    service1_best: "Early startups validating product‑market fit.",
    service1_case: "Case: Koinly — focused tax reporting MVP.",
    service2_title: "UI/UX + Prototype",
    service2_price: "from €X",
    service2_get_1: "User journeys + IA",
    service2_get_2: "Figma design system",
    service2_get_3: "Interactive prototype",
    service2_best: "Founders who need a premium UX before dev.",
    service2_case: "Case: Day’s — calendar‑driven travel UX.",
    service3_title: "Growth & Maintenance",
    service3_price: "from €X / month",
    service3_get_1: "Roadmap + releases",
    service3_get_2: "Analytics + experiments",
    service3_get_3: "Performance & stability",
    service3_best: "Teams scaling after launch.",
    service3_case: "Case: Taskhive — iterative team workflows.",
    process_title: "Process",
    process_subtitle: "A lean, transparent flow that keeps speed and quality in balance.",
    process_1_title: "Discovery call",
    process_1_desc: "We align on goals, scope, and success metrics.",
    process_2_title: "Prototype & plan",
    process_2_desc: "UX flows, timeline, and a roadmap for delivery.",
    process_3_title: "Build & ship",
    process_3_desc: "Engineering, QA, and weekly updates.",
    process_4_title: "Support & iterate",
    process_4_desc: "Growth, improvements, and long‑term support.",
    work_title: "Selected Work",
    work_subtitle: "Problem → Solution → Stack → Outcome.",
    work_problem: "Problem:",
    work_solution: "Solution:",
    work_stack: "Stack:",
    work_outcome: "Outcome:",
    work_koinly_problem: "Complex crypto tax reporting for non‑experts.",
    work_koinly_solution: "Simplified flows with guided import.",
    work_koinly_outcome: "+30% retention (placeholder)",
    work_days_problem: "Visa limits are hard to track across trips.",
    work_days_solution: "Calendar‑based timeline with alerts.",
    work_days_outcome: "+X% engagement (placeholder)",
    work_taskhive_problem: "Teams needed clarity without noisy tools.",
    work_taskhive_solution: "Clean team board with smart filters.",
    work_taskhive_outcome: "+X% activation (placeholder)",
    work_view: "View",
    work_ask: "Ask about similar",
    testimonials_title: "Testimonials",
    testimonials_subtitle: "Social proof placeholders — ready to replace with real quotes.",
    testimonial_1: "“Testimonial placeholder about speed and quality.”",
    testimonial_1_meta: "Founder, Client A",
    testimonial_2: "“Testimonial placeholder about product thinking.”",
    testimonial_2_meta: "CEO, Startup in X",
    testimonial_3: "“Testimonial placeholder about long‑term support.”",
    testimonial_3_meta: "Product Lead, Client B",
    trusted_title: "Trusted by / Worked with",
    faq_title: "FAQ",
    faq_subtitle: "Answers to common questions about timeline, pricing, and delivery.",
    faq_q1: "How long does an MVP take?",
    faq_a1: "Most MVPs ship in 2–4 weeks depending on scope.",
    faq_q2: "How does pricing work?",
    faq_a2: "Fixed‑scope packages or monthly retainers. We start with a brief and estimate.",
    faq_q3: "Do you sign NDAs?",
    faq_a3: "Yes, NDAs are standard for all engagements.",
    faq_q4: "Who owns the code?",
    faq_a4: "You own all IP and source code upon payment.",
    faq_q5: "Do you handle App Store submission?",
    faq_a5: "Yes, we prepare metadata and guide the review process.",
    faq_q6: "What about post‑launch support?",
    faq_a6: "We offer growth and maintenance retainers for ongoing work.",
    faq_q7: "How do we communicate?",
    faq_a7: "Weekly updates, async check‑ins, and a shared project board.",
    contact_title: "Let’s build your MVP",
    contact_subtitle: "Share your idea and get a proposal within a few days.",
    contact_pitch: "We help founders ship fast without sacrificing quality. Send a short brief and we’ll reply with a plan.",
    contact_email: "Email Us",
    contact_telegram: "Telegram",
    contact_linkedin: "LinkedIn",
    form_name: "Name",
    form_email: "Email",
    form_message: "Message",
    form_name_ph: "Your name",
    form_email_ph: "you@email.com",
    form_message_ph: "Briefly describe your product",
    form_submit: "Send request",
    form_note: "We’ll respond within 2–3 business days.",
    form_error: "Please fill all fields.",
    case_type: "Case Study",
    case_mockup: "Project visual placeholder",
    case_problem_title: "Problem",
    case_solution_title: "Solution",
    case_outcome_title: "Outcome",
    case_what_title: "What I did",
    case_what_subtitle: "Scope of work and responsibilities.",
    case_highlights_title: "Highlights",
    case_highlights_subtitle: "Key features or results.",
    case_stack_title: "Stack",
    case_stack_subtitle: "Technologies used for this project.",
    case_screens_title: "Screenshots",
    case_screens_subtitle: "Placeholder images until final assets are ready.",
    case_decisions_title: "Key decisions",
    case_decisions_subtitle: "Tradeoffs and process notes.",
    case_next_title: "Next steps",
    case_next_subtitle: "What’s planned or recommended next.",
    case_cta_title: "Want a similar result?",
    case_cta_subtitle: "Let’s discuss your MVP and the fastest path to launch.",
    case_cta_body: "Share your idea and get a clear plan within days.",
    case_cta_note: "Prefer async? Send a short message and we’ll follow up."
  },
  es: {
    nav_services: "Servicios",
    nav_work: "Trabajo",
    nav_process: "Proceso",
    nav_testimonials: "Testimonios",
    nav_faq: "FAQ",
    nav_contact: "Contacto",
    toggle_theme: "Modo oscuro",
    hero_eyebrow: "Estudio iOS · MVP · Diseño · Backend",
    hero_title: "MVPs iOS para startups — rápidos y bien construidos.",
    hero_subtitle: "Convertimos ideas en productos listos para inversión con alcance claro, diseño premium y tecnología fiable.",
    hero_badge_1: "Entrega rápida",
    hero_badge_2: "Product thinking",
    hero_badge_3: "Equipo iOS senior",
    hero_mockup: "Placeholder de iPhone",
    cta_primary: "Agendar una llamada",
    cta_secondary: "Solicitar propuesta",
    services_title: "Servicios productizados",
    services_subtitle: "Paquetes claros con entregables y presupuestos iniciales.",
    service_what: "Qué recibes",
    service_best: "Ideal para",
    service1_title: "MVP Sprint (2–4 semanas)",
    service1_price: "desde €X",
    service1_get_1: "Flujos clave + onboarding",
    service1_get_2: "Prototipo clicable + backlog",
    service1_get_3: "Build TestFlight",
    service1_best: "Startups en validación de PMF.",
    service1_case: "Caso: Koinly — MVP de reporting fiscal.",
    service2_title: "UI/UX + Prototipo",
    service2_price: "desde €X",
    service2_get_1: "User journeys + IA",
    service2_get_2: "Sistema de diseño en Figma",
    service2_get_3: "Prototipo interactivo",
    service2_best: "Fundadores que necesitan UX premium antes de dev.",
    service2_case: "Caso: Day’s — UX de viajes en calendario.",
    service3_title: "Growth & Mantenimiento",
    service3_price: "desde €X / mes",
    service3_get_1: "Roadmap + releases",
    service3_get_2: "Analítica + experimentos",
    service3_get_3: "Performance y estabilidad",
    service3_best: "Equipos escalando tras el lanzamiento.",
    service3_case: "Caso: Taskhive — iteraciones de workflows.",
    process_title: "Proceso",
    process_subtitle: "Un flujo claro y eficiente para mantener velocidad y calidad.",
    process_1_title: "Discovery call",
    process_1_desc: "Alineamos objetivos, alcance y métricas.",
    process_2_title: "Prototipo y plan",
    process_2_desc: "Flujos UX, timeline y roadmap de entrega.",
    process_3_title: "Construir y lanzar",
    process_3_desc: "Ingeniería, QA y updates semanales.",
    process_4_title: "Soporte e iteración",
    process_4_desc: "Crecimiento, mejoras y soporte continuo.",
    work_title: "Trabajo seleccionado",
    work_subtitle: "Problema → Solución → Stack → Resultado.",
    work_problem: "Problema:",
    work_solution: "Solución:",
    work_stack: "Stack:",
    work_outcome: "Resultado:",
    work_koinly_problem: "Reporting fiscal cripto complejo para usuarios no expertos.",
    work_koinly_solution: "Flujos simplificados con importación guiada.",
    work_koinly_outcome: "+30% retención (placeholder)",
    work_days_problem: "Difícil seguir límites de visado entre viajes.",
    work_days_solution: "Timeline en calendario con alertas.",
    work_days_outcome: "+X% engagement (placeholder)",
    work_taskhive_problem: "Equipos necesitaban claridad sin ruido.",
    work_taskhive_solution: "Tablero limpio con filtros inteligentes.",
    work_taskhive_outcome: "+X% activación (placeholder)",
    work_view: "Ver",
    work_ask: "Consulta similar",
    testimonials_title: "Testimonios",
    testimonials_subtitle: "Placeholders listos para reemplazar por quotes reales.",
    testimonial_1: "“Placeholder sobre velocidad y calidad.”",
    testimonial_1_meta: "Founder, Client A",
    testimonial_2: "“Placeholder sobre enfoque de producto.”",
    testimonial_2_meta: "CEO, Startup in X",
    testimonial_3: "“Placeholder sobre soporte continuo.”",
    testimonial_3_meta: "Product Lead, Client B",
    trusted_title: "Trusted by / Worked with",
    faq_title: "FAQ",
    faq_subtitle: "Respuestas sobre timeline, pricing y delivery.",
    faq_q1: "¿Cuánto tarda un MVP?",
    faq_a1: "La mayoría se entregan en 2–4 semanas según alcance.",
    faq_q2: "¿Cómo funciona el pricing?",
    faq_a2: "Paquetes cerrados o retainer mensual. Empezamos con un brief.",
    faq_q3: "¿Firman NDA?",
    faq_a3: "Sí, es estándar en todos los proyectos.",
    faq_q4: "¿Quién es dueño del código?",
    faq_a4: "El cliente posee todo el IP y el código final.",
    faq_q5: "¿Gestionan el App Store?",
    faq_a5: "Sí, preparamos metadata y guiamos el review.",
    faq_q6: "¿Y el soporte post‑lanzamiento?",
    faq_a6: "Ofrecemos mantenimiento y crecimiento continuo.",
    faq_q7: "¿Cómo nos comunicamos?",
    faq_a7: "Updates semanales y tablero compartido.",
    contact_title: "Construyamos tu MVP",
    contact_subtitle: "Comparte tu idea y recibe una propuesta en pocos días.",
    contact_pitch: "Ayudamos a founders a lanzar rápido sin sacrificar calidad. Envíanos un brief y respondemos con un plan.",
    contact_email: "Email",
    contact_telegram: "Telegram",
    contact_linkedin: "LinkedIn",
    form_name: "Nombre",
    form_email: "Email",
    form_message: "Mensaje",
    form_name_ph: "Tu nombre",
    form_email_ph: "tu@email.com",
    form_message_ph: "Describe tu producto",
    form_submit: "Enviar solicitud",
    form_note: "Respondemos en 2–3 días hábiles.",
    form_error: "Por favor completa todos los campos.",
    case_type: "Caso de estudio",
    case_mockup: "Placeholder visual del proyecto",
    case_problem_title: "Problema",
    case_solution_title: "Solución",
    case_outcome_title: "Resultado",
    case_what_title: "Lo que hice",
    case_what_subtitle: "Alcance y responsabilidades.",
    case_highlights_title: "Highlights",
    case_highlights_subtitle: "Funciones clave o resultados.",
    case_stack_title: "Stack",
    case_stack_subtitle: "Tecnologías usadas en este proyecto.",
    case_screens_title: "Capturas",
    case_screens_subtitle: "Imágenes placeholder hasta tener assets finales.",
    case_decisions_title: "Decisiones clave",
    case_decisions_subtitle: "Notas de proceso y tradeoffs.",
    case_next_title: "Siguientes pasos",
    case_next_subtitle: "Lo que sigue o se recomienda.",
    case_cta_title: "¿Quieres un resultado similar?",
    case_cta_subtitle: "Hablemos de tu MVP y el camino más rápido al lanzamiento.",
    case_cta_body: "Comparte tu idea y recibe un plan en pocos días.",
    case_cta_note: "¿Prefieres async? Envíanos un mensaje y respondemos."
  },
  ru: {
    nav_services: "Услуги",
    nav_work: "Проекты",
    nav_process: "Процесс",
    nav_testimonials: "Отзывы",
    nav_faq: "FAQ",
    nav_contact: "Контакты",
    toggle_theme: "Тёмная тема",
    hero_eyebrow: "iOS Studio · MVP · Дизайн · Backend",
    hero_title: "iOS MVP для стартапов — быстро и качественно.",
    hero_subtitle: "Превращаем идеи в продукты для инвесторов: чёткий объём, премиальный дизайн и надёжная разработка.",
    hero_badge_1: "Быстрый запуск",
    hero_badge_2: "Product thinking",
    hero_badge_3: "Senior iOS команда",
    hero_mockup: "Плейсхолдер айфона",
    cta_primary: "Запросить консультацию",
    cta_secondary: "Получить смету",
    services_title: "Продуктовые пакеты",
    services_subtitle: "Понятные пакеты с результатами и стартовыми бюджетами.",
    service_what: "Что входит",
    service_best: "Лучше всего",
    service1_title: "MVP Sprint (2–4 недели)",
    service1_price: "от €X",
    service1_get_1: "Ключевые сценарии + онбординг",
    service1_get_2: "Кликабельный прототип + бэклог",
    service1_get_3: "Сборка TestFlight",
    service1_best: "Для стартапов на проверке PMF.",
    service1_case: "Кейс: Koinly — MVP отчётности.",
    service2_title: "UI/UX + прототип",
    service2_price: "от €X",
    service2_get_1: "Пользовательские сценарии + IA",
    service2_get_2: "Дизайн‑система в Figma",
    service2_get_3: "Интерактивный прототип",
    service2_best: "Фаундерам, которым нужен сильный UX до разработки.",
    service2_case: "Кейс: Day’s — календарный UX путешествий.",
    service3_title: "Рост и поддержка",
    service3_price: "от €X / месяц",
    service3_get_1: "Роадмап + релизы",
    service3_get_2: "Аналитика + эксперименты",
    service3_get_3: "Производительность и стабильность",
    service3_best: "Командам после запуска.",
    service3_case: "Кейс: Taskhive — итерации рабочих процессов.",
    process_title: "Процесс",
    process_subtitle: "Прозрачный и быстрый цикл работы.",
    process_1_title: "Discovery созвон",
    process_1_desc: "Согласуем цели, объём и метрики успеха.",
    process_2_title: "Прототип и план",
    process_2_desc: "UX, сроки и план поставки.",
    process_3_title: "Разработка и запуск",
    process_3_desc: "Инженерия, QA, еженедельные апдейты.",
    process_4_title: "Поддержка и рост",
    process_4_desc: "Развитие продукта после релиза.",
    work_title: "Избранные проекты",
    work_subtitle: "Проблема → Решение → Стек → Результат.",
    work_problem: "Проблема:",
    work_solution: "Решение:",
    work_stack: "Стек:",
    work_outcome: "Результат:",
    work_koinly_problem: "Сложная крипто‑отчётность для обычных пользователей.",
    work_koinly_solution: "Упрощённые сценарии с импортом данных.",
    work_koinly_outcome: "+30% удержание (плейсхолдер)",
    work_days_problem: "Сложно отслеживать визовые лимиты между поездками.",
    work_days_solution: "Календарь и уведомления по срокам.",
    work_days_outcome: "+X% вовлечённость (плейсхолдер)",
    work_taskhive_problem: "Командам нужна ясность без шума.",
    work_taskhive_solution: "Чистая доска задач с фильтрами.",
    work_taskhive_outcome: "+X% активация (плейсхолдер)",
    work_view: "Смотреть",
    work_ask: "Спросить похожее",
    testimonials_title: "Отзывы",
    testimonials_subtitle: "Плейсхолдеры — заменим на реальные цитаты.",
    testimonial_1: "“Плейсхолдер про скорость и качество.”",
    testimonial_1_meta: "Founder, Client A",
    testimonial_2: "“Плейсхолдер про продуктовый подход.”",
    testimonial_2_meta: "CEO, Startup in X",
    testimonial_3: "“Плейсхолдер про поддержку после релиза.”",
    testimonial_3_meta: "Product Lead, Client B",
    trusted_title: "Trusted by / Worked with",
    faq_title: "FAQ",
    faq_subtitle: "Ответы о сроках, бюджете и процессе.",
    faq_q1: "Сколько занимает MVP?",
    faq_a1: "Обычно 2–4 недели в зависимости от объёма.",
    faq_q2: "Как формируется цена?",
    faq_a2: "Фиксированный пакет или ежемесячный ретейнер. Начинаем с брифа.",
    faq_q3: "Работаете по NDA?",
    faq_a3: "Да, NDA — стандарт.",
    faq_q4: "Кому принадлежит код?",
    faq_a4: "Весь IP и код — ваши после оплаты.",
    faq_q5: "Помогаете с App Store?",
    faq_a5: "Да, готовим метаданные и ведём ревью.",
    faq_q6: "Есть ли поддержка после запуска?",
    faq_a6: "Да, предлагаем сопровождение и рост.",
    faq_q7: "Как выстроена коммуникация?",
    faq_a7: "Еженедельные апдейты и общий трекер.",
    contact_title: "Давайте соберём ваш MVP",
    contact_subtitle: "Опишите идею и получите предложение за несколько дней.",
    contact_pitch: "Помогаем фаундерам запускаться быстро и без потери качества. Отправьте краткий бриф — вернёмся с планом.",
    contact_email: "Почта",
    contact_telegram: "Telegram",
    contact_linkedin: "LinkedIn",
    form_name: "Имя",
    form_email: "Email",
    form_message: "Сообщение",
    form_name_ph: "Ваше имя",
    form_email_ph: "you@email.com",
    form_message_ph: "Кратко опишите продукт",
    form_submit: "Отправить запрос",
    form_note: "Ответим в течение 2–3 рабочих дней.",
    form_error: "Пожалуйста, заполните все поля.",
    case_type: "Кейс",
    case_mockup: "Плейсхолдер визуала проекта",
    case_problem_title: "Проблема",
    case_solution_title: "Решение",
    case_outcome_title: "Результат",
    case_what_title: "Что делал",
    case_what_subtitle: "Объём работ и зоны ответственности.",
    case_highlights_title: "Ключевые моменты",
    case_highlights_subtitle: "Функции и результаты.",
    case_stack_title: "Стек",
    case_stack_subtitle: "Технологии проекта.",
    case_screens_title: "Скриншоты",
    case_screens_subtitle: "Плейсхолдеры до готовых ассетов.",
    case_decisions_title: "Ключевые решения",
    case_decisions_subtitle: "Трейд‑оффы и заметки по процессу.",
    case_next_title: "Следующие шаги",
    case_next_subtitle: "Что планируется дальше.",
    case_cta_title: "Нужен похожий результат?",
    case_cta_subtitle: "Обсудим MVP и самый быстрый путь к запуску.",
    case_cta_body: "Расскажите идею — подготовим план за несколько дней.",
    case_cta_note: "Предпочитаете асинхронно? Напишите, и мы ответим."
  }
};

const langButtons = document.querySelectorAll(".lang-switch button");
const themeToggle = document.getElementById("themeToggle");
let currentLang = "en";

function applyTranslations(lang) {
  const t = translations[lang] || translations.en;
  currentLang = lang;
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    if (t[key]) {
      el.textContent = t[key];
    }
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
    const key = el.getAttribute("data-i18n-placeholder");
    if (t[key]) {
      el.setAttribute("placeholder", t[key]);
    }
  });
  localStorage.setItem("lang", lang);
}

function mergePageTranslations() {
  if (!window.pageTranslations) {
    return;
  }
  ["en", "es", "ru"].forEach((lang) => {
    const page = window.pageTranslations[lang];
    if (page) {
      translations[lang] = { ...translations[lang], ...page };
    }
  });
}

mergePageTranslations();

function setTheme(isDark) {
  document.body.classList.toggle("dark", isDark);
  localStorage.setItem("theme", isDark ? "dark" : "light");
}

langButtons.forEach((btn) => {
  btn.addEventListener("click", () => applyTranslations(btn.dataset.lang));
});

const savedLang = localStorage.getItem("lang") || "en";
applyTranslations(savedLang);

const prefersDark = window.matchMedia("(prefers-color-scheme: dark)");
const savedTheme = localStorage.getItem("theme");
if (savedTheme) {
  setTheme(savedTheme === "dark");
} else {
  setTheme(prefersDark.matches);
}

prefersDark.addEventListener("change", (event) => {
  if (!localStorage.getItem("theme")) {
    setTheme(event.matches);
  }
});

themeToggle.addEventListener("click", () => {
  const isDark = document.body.classList.contains("dark");
  setTheme(!isDark);
});

const form = document.getElementById("contactForm");
form.addEventListener("submit", (e) => {
  const name = form.querySelector("#name");
  const email = form.querySelector("#email");
  const message = form.querySelector("#message");
  if (!name.value.trim() || !email.value.trim() || !message.value.trim()) {
    e.preventDefault();
    const t = translations[currentLang] || translations.en;
    alert(t.form_error || "Please fill all fields.");
  }
});
